package com.pojo;

import java.util.ArrayList;
import java.util.List;

public class EmployeeExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table employee
     *
     * @mbg.generated Thu Nov 11 11:37:17 CST 2021
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table employee
     *
     * @mbg.generated Thu Nov 11 11:37:17 CST 2021
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table employee
     *
     * @mbg.generated Thu Nov 11 11:37:17 CST 2021
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbg.generated Thu Nov 11 11:37:17 CST 2021
     */
    public EmployeeExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbg.generated Thu Nov 11 11:37:17 CST 2021
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbg.generated Thu Nov 11 11:37:17 CST 2021
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbg.generated Thu Nov 11 11:37:17 CST 2021
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbg.generated Thu Nov 11 11:37:17 CST 2021
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbg.generated Thu Nov 11 11:37:17 CST 2021
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbg.generated Thu Nov 11 11:37:17 CST 2021
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbg.generated Thu Nov 11 11:37:17 CST 2021
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbg.generated Thu Nov 11 11:37:17 CST 2021
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbg.generated Thu Nov 11 11:37:17 CST 2021
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbg.generated Thu Nov 11 11:37:17 CST 2021
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table employee
     *
     * @mbg.generated Thu Nov 11 11:37:17 CST 2021
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andEmployeeIdIsNull() {
            addCriterion("employee_id is null");
            return (Criteria) this;
        }

        public Criteria andEmployeeIdIsNotNull() {
            addCriterion("employee_id is not null");
            return (Criteria) this;
        }

        public Criteria andEmployeeIdEqualTo(Integer value) {
            addCriterion("employee_id =", value, "employeeId");
            return (Criteria) this;
        }

        public Criteria andEmployeeIdNotEqualTo(Integer value) {
            addCriterion("employee_id <>", value, "employeeId");
            return (Criteria) this;
        }

        public Criteria andEmployeeIdGreaterThan(Integer value) {
            addCriterion("employee_id >", value, "employeeId");
            return (Criteria) this;
        }

        public Criteria andEmployeeIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("employee_id >=", value, "employeeId");
            return (Criteria) this;
        }

        public Criteria andEmployeeIdLessThan(Integer value) {
            addCriterion("employee_id <", value, "employeeId");
            return (Criteria) this;
        }

        public Criteria andEmployeeIdLessThanOrEqualTo(Integer value) {
            addCriterion("employee_id <=", value, "employeeId");
            return (Criteria) this;
        }

        public Criteria andEmployeeIdIn(List<Integer> values) {
            addCriterion("employee_id in", values, "employeeId");
            return (Criteria) this;
        }

        public Criteria andEmployeeIdNotIn(List<Integer> values) {
            addCriterion("employee_id not in", values, "employeeId");
            return (Criteria) this;
        }

        public Criteria andEmployeeIdBetween(Integer value1, Integer value2) {
            addCriterion("employee_id between", value1, value2, "employeeId");
            return (Criteria) this;
        }

        public Criteria andEmployeeIdNotBetween(Integer value1, Integer value2) {
            addCriterion("employee_id not between", value1, value2, "employeeId");
            return (Criteria) this;
        }

        public Criteria andEmployeeNameIsNull() {
            addCriterion("employee_name is null");
            return (Criteria) this;
        }

        public Criteria andEmployeeNameIsNotNull() {
            addCriterion("employee_name is not null");
            return (Criteria) this;
        }

        public Criteria andEmployeeNameEqualTo(String value) {
            addCriterion("employee_name =", value, "employeeName");
            return (Criteria) this;
        }

        public Criteria andEmployeeNameNotEqualTo(String value) {
            addCriterion("employee_name <>", value, "employeeName");
            return (Criteria) this;
        }

        public Criteria andEmployeeNameGreaterThan(String value) {
            addCriterion("employee_name >", value, "employeeName");
            return (Criteria) this;
        }

        public Criteria andEmployeeNameGreaterThanOrEqualTo(String value) {
            addCriterion("employee_name >=", value, "employeeName");
            return (Criteria) this;
        }

        public Criteria andEmployeeNameLessThan(String value) {
            addCriterion("employee_name <", value, "employeeName");
            return (Criteria) this;
        }

        public Criteria andEmployeeNameLessThanOrEqualTo(String value) {
            addCriterion("employee_name <=", value, "employeeName");
            return (Criteria) this;
        }

        public Criteria andEmployeeNameLike(String value) {
            addCriterion("employee_name like", value, "employeeName");
            return (Criteria) this;
        }

        public Criteria andEmployeeNameNotLike(String value) {
            addCriterion("employee_name not like", value, "employeeName");
            return (Criteria) this;
        }

        public Criteria andEmployeeNameIn(List<String> values) {
            addCriterion("employee_name in", values, "employeeName");
            return (Criteria) this;
        }

        public Criteria andEmployeeNameNotIn(List<String> values) {
            addCriterion("employee_name not in", values, "employeeName");
            return (Criteria) this;
        }

        public Criteria andEmployeeNameBetween(String value1, String value2) {
            addCriterion("employee_name between", value1, value2, "employeeName");
            return (Criteria) this;
        }

        public Criteria andEmployeeNameNotBetween(String value1, String value2) {
            addCriterion("employee_name not between", value1, value2, "employeeName");
            return (Criteria) this;
        }

        public Criteria andEmployeeTelephoneIsNull() {
            addCriterion("employee_telephone is null");
            return (Criteria) this;
        }

        public Criteria andEmployeeTelephoneIsNotNull() {
            addCriterion("employee_telephone is not null");
            return (Criteria) this;
        }

        public Criteria andEmployeeTelephoneEqualTo(String value) {
            addCriterion("employee_telephone =", value, "employeeTelephone");
            return (Criteria) this;
        }

        public Criteria andEmployeeTelephoneNotEqualTo(String value) {
            addCriterion("employee_telephone <>", value, "employeeTelephone");
            return (Criteria) this;
        }

        public Criteria andEmployeeTelephoneGreaterThan(String value) {
            addCriterion("employee_telephone >", value, "employeeTelephone");
            return (Criteria) this;
        }

        public Criteria andEmployeeTelephoneGreaterThanOrEqualTo(String value) {
            addCriterion("employee_telephone >=", value, "employeeTelephone");
            return (Criteria) this;
        }

        public Criteria andEmployeeTelephoneLessThan(String value) {
            addCriterion("employee_telephone <", value, "employeeTelephone");
            return (Criteria) this;
        }

        public Criteria andEmployeeTelephoneLessThanOrEqualTo(String value) {
            addCriterion("employee_telephone <=", value, "employeeTelephone");
            return (Criteria) this;
        }

        public Criteria andEmployeeTelephoneLike(String value) {
            addCriterion("employee_telephone like", value, "employeeTelephone");
            return (Criteria) this;
        }

        public Criteria andEmployeeTelephoneNotLike(String value) {
            addCriterion("employee_telephone not like", value, "employeeTelephone");
            return (Criteria) this;
        }

        public Criteria andEmployeeTelephoneIn(List<String> values) {
            addCriterion("employee_telephone in", values, "employeeTelephone");
            return (Criteria) this;
        }

        public Criteria andEmployeeTelephoneNotIn(List<String> values) {
            addCriterion("employee_telephone not in", values, "employeeTelephone");
            return (Criteria) this;
        }

        public Criteria andEmployeeTelephoneBetween(String value1, String value2) {
            addCriterion("employee_telephone between", value1, value2, "employeeTelephone");
            return (Criteria) this;
        }

        public Criteria andEmployeeTelephoneNotBetween(String value1, String value2) {
            addCriterion("employee_telephone not between", value1, value2, "employeeTelephone");
            return (Criteria) this;
        }

        public Criteria andEmployeeDepartmentIsNull() {
            addCriterion("employee_department is null");
            return (Criteria) this;
        }

        public Criteria andEmployeeDepartmentIsNotNull() {
            addCriterion("employee_department is not null");
            return (Criteria) this;
        }

        public Criteria andEmployeeDepartmentEqualTo(Integer value) {
            addCriterion("employee_department =", value, "employeeDepartment");
            return (Criteria) this;
        }

        public Criteria andEmployeeDepartmentNotEqualTo(Integer value) {
            addCriterion("employee_department <>", value, "employeeDepartment");
            return (Criteria) this;
        }

        public Criteria andEmployeeDepartmentGreaterThan(Integer value) {
            addCriterion("employee_department >", value, "employeeDepartment");
            return (Criteria) this;
        }

        public Criteria andEmployeeDepartmentGreaterThanOrEqualTo(Integer value) {
            addCriterion("employee_department >=", value, "employeeDepartment");
            return (Criteria) this;
        }

        public Criteria andEmployeeDepartmentLessThan(Integer value) {
            addCriterion("employee_department <", value, "employeeDepartment");
            return (Criteria) this;
        }

        public Criteria andEmployeeDepartmentLessThanOrEqualTo(Integer value) {
            addCriterion("employee_department <=", value, "employeeDepartment");
            return (Criteria) this;
        }

        public Criteria andEmployeeDepartmentIn(List<Integer> values) {
            addCriterion("employee_department in", values, "employeeDepartment");
            return (Criteria) this;
        }

        public Criteria andEmployeeDepartmentNotIn(List<Integer> values) {
            addCriterion("employee_department not in", values, "employeeDepartment");
            return (Criteria) this;
        }

        public Criteria andEmployeeDepartmentBetween(Integer value1, Integer value2) {
            addCriterion("employee_department between", value1, value2, "employeeDepartment");
            return (Criteria) this;
        }

        public Criteria andEmployeeDepartmentNotBetween(Integer value1, Integer value2) {
            addCriterion("employee_department not between", value1, value2, "employeeDepartment");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table employee
     *
     * @mbg.generated do_not_delete_during_merge Thu Nov 11 11:37:17 CST 2021
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table employee
     *
     * @mbg.generated Thu Nov 11 11:37:17 CST 2021
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}